# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hamburger 2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hamburger 2
    # Pods for UI
	   pod 'HMSegmentedControl'
     pod 'BTNavigationDropdownMenu', :git => 'https://github.com/zkrige/BTNavigationDropdownMenu.git'
    # Pods for Firebase
      pod 'Firebase/Core'
      pod 'Firebase/Auth'
      pod 'Firebase/Database'
    # Pods for Facebook API
      pod 'FacebookCore'
      pod 'FacebookLogin'
      pod 'FacebookShare'
    # Pods for Twitter API
      pod 'TwitterKit'
    # Pods for Mixpanel
      pod 'Mixpanel'

end
